from ...sys.iroha_data_model.isi import (
    BurnBox as Burn,
    FailBox as Fail,
    GrantBox as Grant,
    MintBox as Mint,
    RegisterBox as Register,
    RemoveKeyValueBox as RemoveKeyValue,
    SequenceBox as Sequence,
    SetKeyValueBox as SetKeyValue,
    TransferBox as Transfer,
    UnregisterBox as Unregister,
    If,
    Instruction,
    Pair,
)
