from ...rust import Enum, Struct, Tuple, Dict

QueryBox = Enum[
    ("FindAllAccounts", "iroha_data_model.query.account.FindAllAccounts"),
    ("FindAccountById", "iroha_data_model.query.account.FindAccountById"),
    ("FindAccountKeyValueByIdAndKey",
     "iroha_data_model.query.account.FindAccountKeyValueByIdAndKey"),
    ("FindAccountsByName",
     "iroha_data_model.query.account.FindAccountsByName"),
    ("FindAccountsByDomainName",
     "iroha_data_model.query.account.FindAccountsByDomainName"),
    ("FindAllAssets", "iroha_data_model.query.asset.FindAllAssets"),
    ("FindAllAssetsDefinitions",
     "iroha_data_model.query.asset.FindAllAssetsDefinitions"),
    ("FindAssetById", "iroha_data_model.query.asset.FindAssetById"),
    ("FindAssetsByName", "iroha_data_model.query.asset.FindAssetsByName"),
    ("FindAssetsByAccountId",
     "iroha_data_model.query.asset.FindAssetsByAccountId"),
    ("FindAssetsByAssetDefinitionId",
     "iroha_data_model.query.asset.FindAssetsByAssetDefinitionId"),
    ("FindAssetsByDomainName",
     "iroha_data_model.query.asset.FindAssetsByDomainName"),
    ("FindAssetsByDomainNameAndAssetDefinitionId",
     "iroha_data_model.query.asset.FindAssetsByDomainNameAndAssetDefinitionId"
     ), ("FindAssetQuantityById",
         "iroha_data_model.query.asset.FindAssetQuantityById"),
    ("FindAssetKeyValueByIdAndKey",
     "iroha_data_model.query.asset.FindAssetKeyValueByIdAndKey"),
    ("FindAssetDefinitionKeyValueByIdAndKey",
     "iroha_data_model.query.asset.FindAssetDefinitionKeyValueByIdAndKey"),
    ("FindAllDomains", "iroha_data_model.query.domain.FindAllDomains"),
    ("FindDomainByName", "iroha_data_model.query.domain.FindDomainByName"),
    ("FindDomainKeyValueByIdAndKey",
     "iroha_data_model.query.domain.FindDomainKeyValueByIdAndKey"),
    ("FindAllPeers", "iroha_data_model.query.peer.FindAllPeers"),
    ("FindTransactionsByAccountId",
     "iroha_data_model.query.transaction.FindTransactionsByAccountId"),
    ("FindTransactionByHash",
     "iroha_data_model.query.transaction.FindTransactionByHash"),
    ("FindPermissionTokensByAccountId",
     "iroha_data_model.query.permissions.FindPermissionTokensByAccountId")]
