# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: block.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import primitive_pb2 as primitive__pb2
from . import transaction_pb2 as transaction__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62lock.proto\x12\x0eiroha.protocol\x1a\x0fprimitive.proto\x1a\x11transaction.proto\"\xa3\x02\n\x08\x42lock_v1\x12\x31\n\x07payload\x18\x01 \x01(\x0b\x32 .iroha.protocol.Block_v1.Payload\x12-\n\nsignatures\x18\x02 \x03(\x0b\x32\x19.iroha.protocol.Signature\x1a\xb4\x01\n\x07Payload\x12\x31\n\x0ctransactions\x18\x01 \x03(\x0b\x32\x1b.iroha.protocol.Transaction\x12\x11\n\ttx_number\x18\x02 \x01(\r\x12\x0e\n\x06height\x18\x03 \x01(\x04\x12\x17\n\x0fprev_block_hash\x18\x04 \x01(\t\x12\x14\n\x0c\x63reated_time\x18\x05 \x01(\x04\x12$\n\x1crejected_transactions_hashes\x18\x06 \x03(\t\"F\n\x05\x42lock\x12,\n\x08\x62lock_v1\x18\x01 \x01(\x0b\x32\x18.iroha.protocol.Block_v1H\x00\x42\x0f\n\rblock_versionB\x1aZ\x18iroha.generated/protocolb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'block_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\030iroha.generated/protocol'
  _globals['_BLOCK_V1']._serialized_start=68
  _globals['_BLOCK_V1']._serialized_end=359
  _globals['_BLOCK_V1_PAYLOAD']._serialized_start=179
  _globals['_BLOCK_V1_PAYLOAD']._serialized_end=359
  _globals['_BLOCK']._serialized_start=361
  _globals['_BLOCK']._serialized_end=431
# @@protoc_insertion_point(module_scope)
