# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: endpoint.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import transaction_pb2 as transaction__pb2
from . import queries_pb2 as queries__pb2
from . import qry_responses_pb2 as qry__responses__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65ndpoint.proto\x12\x0eiroha.protocol\x1a\x11transaction.proto\x1a\rqueries.proto\x1a\x13qry_responses.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x94\x01\n\rToriiResponse\x12+\n\ttx_status\x18\x01 \x01(\x0e\x32\x18.iroha.protocol.TxStatus\x12\x0f\n\x07tx_hash\x18\x02 \x01(\t\x12\x17\n\x0f\x65rr_or_cmd_name\x18\x03 \x01(\t\x12\x18\n\x10\x66\x61iled_cmd_index\x18\x04 \x01(\x04\x12\x12\n\nerror_code\x18\x05 \x01(\r\"\"\n\x0fTxStatusRequest\x12\x0f\n\x07tx_hash\x18\x01 \x01(\t\";\n\x06TxList\x12\x31\n\x0ctransactions\x18\x01 \x03(\x0b\x32\x1b.iroha.protocol.Transaction*\x80\x02\n\x08TxStatus\x12\x1f\n\x1bSTATELESS_VALIDATION_FAILED\x10\x00\x12 \n\x1cSTATELESS_VALIDATION_SUCCESS\x10\x01\x12\x1e\n\x1aSTATEFUL_VALIDATION_FAILED\x10\x02\x12\x1f\n\x1bSTATEFUL_VALIDATION_SUCCESS\x10\x03\x12\x0c\n\x08REJECTED\x10\x04\x12\r\n\tCOMMITTED\x10\x05\x12\x0f\n\x0bMST_EXPIRED\x10\x06\x12\x10\n\x0cNOT_RECEIVED\x10\x07\x12\x0f\n\x0bMST_PENDING\x10\x08\x12\x1f\n\x1b\x45NOUGH_SIGNATURES_COLLECTED\x10\t2\xaa\x02\n\x11\x43ommandService_v1\x12<\n\x05Torii\x12\x1b.iroha.protocol.Transaction\x1a\x16.google.protobuf.Empty\x12;\n\tListTorii\x12\x16.iroha.protocol.TxList\x1a\x16.google.protobuf.Empty\x12H\n\x06Status\x12\x1f.iroha.protocol.TxStatusRequest\x1a\x1d.iroha.protocol.ToriiResponse\x12P\n\x0cStatusStream\x12\x1f.iroha.protocol.TxStatusRequest\x1a\x1d.iroha.protocol.ToriiResponse0\x01\x32\xea\x01\n\x0fQueryService_v1\x12<\n\x04\x46ind\x12\x15.iroha.protocol.Query\x1a\x1d.iroha.protocol.QueryResponse\x12Q\n\x0c\x46\x65tchCommits\x12\x1b.iroha.protocol.BlocksQuery\x1a\".iroha.protocol.BlockQueryResponse0\x01\x12\x46\n\x0bHealthcheck\x12\x16.google.protobuf.Empty\x1a\x1f.iroha.protocol.HealthcheckDataB\x1aZ\x18iroha.generated/protocolb\x06proto3')

_TXSTATUS = DESCRIPTOR.enum_types_by_name['TxStatus']
TxStatus = enum_type_wrapper.EnumTypeWrapper(_TXSTATUS)
STATELESS_VALIDATION_FAILED = 0
STATELESS_VALIDATION_SUCCESS = 1
STATEFUL_VALIDATION_FAILED = 2
STATEFUL_VALIDATION_SUCCESS = 3
REJECTED = 4
COMMITTED = 5
MST_EXPIRED = 6
NOT_RECEIVED = 7
MST_PENDING = 8
ENOUGH_SIGNATURES_COLLECTED = 9


_TORIIRESPONSE = DESCRIPTOR.message_types_by_name['ToriiResponse']
_TXSTATUSREQUEST = DESCRIPTOR.message_types_by_name['TxStatusRequest']
_TXLIST = DESCRIPTOR.message_types_by_name['TxList']
ToriiResponse = _reflection.GeneratedProtocolMessageType('ToriiResponse', (_message.Message,), {
  'DESCRIPTOR' : _TORIIRESPONSE,
  '__module__' : 'endpoint_pb2'
  # @@protoc_insertion_point(class_scope:iroha.protocol.ToriiResponse)
  })
_sym_db.RegisterMessage(ToriiResponse)

TxStatusRequest = _reflection.GeneratedProtocolMessageType('TxStatusRequest', (_message.Message,), {
  'DESCRIPTOR' : _TXSTATUSREQUEST,
  '__module__' : 'endpoint_pb2'
  # @@protoc_insertion_point(class_scope:iroha.protocol.TxStatusRequest)
  })
_sym_db.RegisterMessage(TxStatusRequest)

TxList = _reflection.GeneratedProtocolMessageType('TxList', (_message.Message,), {
  'DESCRIPTOR' : _TXLIST,
  '__module__' : 'endpoint_pb2'
  # @@protoc_insertion_point(class_scope:iroha.protocol.TxList)
  })
_sym_db.RegisterMessage(TxList)

_COMMANDSERVICE_V1 = DESCRIPTOR.services_by_name['CommandService_v1']
_QUERYSERVICE_V1 = DESCRIPTOR.services_by_name['QueryService_v1']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\030iroha.generated/protocol'
  _TXSTATUS._serialized_start=367
  _TXSTATUS._serialized_end=623
  _TORIIRESPONSE._serialized_start=119
  _TORIIRESPONSE._serialized_end=267
  _TXSTATUSREQUEST._serialized_start=269
  _TXSTATUSREQUEST._serialized_end=303
  _TXLIST._serialized_start=305
  _TXLIST._serialized_end=364
  _COMMANDSERVICE_V1._serialized_start=626
  _COMMANDSERVICE_V1._serialized_end=924
  _QUERYSERVICE_V1._serialized_start=927
  _QUERYSERVICE_V1._serialized_end=1161
# @@protoc_insertion_point(module_scope)
