# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proposal.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import transaction_pb2 as transaction__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proposal.proto',
  package='iroha.protocol',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0eproposal.proto\x12\x0eiroha.protocol\x1a\x11transaction.proto\"c\n\x08Proposal\x12\x0e\n\x06height\x18\x01 \x01(\x04\x12\x31\n\x0ctransactions\x18\x02 \x03(\x0b\x32\x1b.iroha.protocol.Transaction\x12\x14\n\x0c\x63reated_time\x18\x03 \x01(\x04\x62\x06proto3')
  ,
  dependencies=[transaction__pb2.DESCRIPTOR,])




_PROPOSAL = _descriptor.Descriptor(
  name='Proposal',
  full_name='iroha.protocol.Proposal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='height', full_name='iroha.protocol.Proposal.height', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='transactions', full_name='iroha.protocol.Proposal.transactions', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created_time', full_name='iroha.protocol.Proposal.created_time', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=152,
)

_PROPOSAL.fields_by_name['transactions'].message_type = transaction__pb2._TRANSACTION
DESCRIPTOR.message_types_by_name['Proposal'] = _PROPOSAL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Proposal = _reflection.GeneratedProtocolMessageType('Proposal', (_message.Message,), dict(
  DESCRIPTOR = _PROPOSAL,
  __module__ = 'proposal_pb2'
  # @@protoc_insertion_point(class_scope:iroha.protocol.Proposal)
  ))
_sym_db.RegisterMessage(Proposal)


# @@protoc_insertion_point(module_scope)
